### ISSUE TITLE
not working for me on warmane-blackrock

### ISSUE THREAD

**Issue by suz-png** [Cortes-Jeremy/WotLK-Patch#4]
Hi, i tried to copy Patch-xxx.MPQ here : 

![image](https://user-images.githubusercontent.com/101992738/159250917-462c9367-8e00-40cd-bdcb-5c2501a48d3b.png)

but it doesnt work
do i have to install a soft or something before installing ?

**Comment by Cortes-Jeremy** [comment]
Hi, the patch need to be renamed with a number or letter: exemple "patch-Dalaran.mpq" become: "patch-A.mpq" and "patch-Nagrand.mpq" become: "patch-B.mpq".
Hope this help.

**Comment by suz-png** [comment]
Thank you !
Have a good day
